In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import os
import shutil
import mne


In [2]:
session_count = 3

In [3]:
# Store paths to base, train set and subset dirs
base_dir = "/kaggle/input/inner-speech-recognition"
train_dir = base_dir + "/inner-speech-recognition/derivatives/sub-01"
subset_dir = "/kaggle/working/data"

if not os.path.exists(subset_dir):
    os.mkdir(subset_dir)
    print(subset_dir, "created!")
else:
    print(subset_dir, "already exists!")
    
# Select only first n class dirs
class_dirs = os.listdir(train_dir)[:session_count]

# Copy class dir from train set to working dir
for class_dir in class_dirs:
    # Define current source and destination paths
    source_dir = train_dir + "/" + class_dir
    destination_dir = subset_dir + "/" + class_dir
    
    # If new class, copy to working dir
    if not os.path.exists(destination_dir):
        shutil.copytree(source_dir, destination_dir)
        print(class_dir, "succesfully copied!")
    # If it exists, don't copy again
    else:
        print(class_dir, "doesn't need copying!")

/kaggle/working/data created!
ses-02 succesfully copied!
ses-01 succesfully copied!
ses-03 succesfully copied!


In [4]:
eeg_epochs = mne.read_epochs(subset_dir + '/ses-01/sub-01_ses-01_eeg-epo.fif')


Reading /kaggle/working/data/ses-01/sub-01_ses-01_eeg-epo.fif ...
Isotrak not found
    Found the data of interest:
        t =    -500.00 ...    4000.00 ms
        0 CTF compensation matrices available
Not setting metadata
200 matching events found
No baseline correction applied
0 projection items activated


In [5]:
with open('/kaggle/working/data/ses-01/sub-01_ses-01_events.dat', 'rb') as f:
  text = f.read()

In [6]:
events_eeg = np.load('/kaggle/working/data/ses-01/sub-01_ses-01_events.dat',allow_pickle=True)

In [7]:
print(events_eeg)

[[  39869       3       0       1]
 [  46491       0       0       1]
 [  53010       3       0       1]
 [  59649       3       0       1]
 [  66270       2       0       1]
 [  73063       1       0       1]
 [  79838       3       0       1]
 [  86528       1       0       1]
 [  93064       3       0       1]
 [  99823       1       0       1]
 [ 106461       0       0       1]
 [ 113015       0       0       1]
 [ 119824       3       0       1]
 [ 126651       2       0       1]
 [ 133289       1       0       1]
 [ 139996       0       0       1]
 [ 146669       0       0       1]
 [ 153154       3       0       1]
 [ 159691       1       0       1]
 [ 166295       3       0       1]
 [ 172815       1       0       1]
 [ 179641       2       0       1]
 [ 186109       1       0       1]
 [ 192612       0       0       1]
 [ 199080       2       0       1]
 [ 205582       2       0       1]
 [ 212169       1       0       1]
 [ 218723       0       0       1]
 [ 225583       2   